### ISSUE TITLE
Allow different distance metrics parametrizations for different coordinate systems

### ISSUE THREAD

**Issue by codehippo** [tom-whitehead/hdbscan#15]
Hello! Let me start by expressing gratitude for this great crate!

However, I'd love to use this crate for a custom color palette generation via image color quantization. I'd love to make this using the HDBSCAN algorithm in the [OKL<sub>r</sub>CH](https://bottosson.github.io/posts/colorpicker/) space but the space uses cylindrical coordinates.

I could probably convert these back to Cartesian coordinates before going to clustering. This would work but I'd love to play around different non-euclidean metrics so as to discriminate against dark tones etc. which is easiest when having the possibility to set the distance metric yourself by (for example) supplying a closure.

Maybe adding a fourth option to `DistanceMetric` enum for `Custom` and then letting the user supply the implementation themselves?

**Comment by tom-whitehead** [comment]
Hey @codehippo, thank you for raising an issue! To be honest with you I hadn't even heard of cylindrical coordinates, everything I cluster is firmly in cartesian spaces. 
All that is required to make this work is a distance function. I like the idea you suggest of having a means of providing a custom distance function as this makes the crate more flexible.
I'm quite busy with work until the latter half of the week, but I will try and take a look at this before the weekend :)

**Comment by tom-whitehead** [comment]
Hey @codehippo, I've added a cylindrical distance option for you to use. Hopefully it's quite straight forward but you can refer to [this](https://github.com/tom-whitehead/hdbscan/blob/master/src/lib.rs#L1030) test to see how to use it. Note that the coordinates need to be in the order radial distance, angular coordinate, height, so HSV colours would need to be reordered to SHV. 
Hope you find this useful.
